config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("todo.urls", namespace="todo")),
    path("user/", include("user.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todo/urls.py
from django.urls import path
from . import views

app_name = "todo"

urlpatterns = [
    path("", views.home_view, name="home"),
    path("detail/<int:id>", views.detail_view, name="detail"),
    # todo
    path("create/", views.create_view, name="create"),
    path("update/<int:id>", views.update_view, name="update"),
    path("delete/<int:id>", views.delete_view, name="delete"),
    path("mypage/", views.mypage_view, name="mypage"),
    path("likes/<int:id>", views.likes_view, name="likes"),
    # comment
    path("<int:todo_id>/create", views.create_comment_view, name="create_comment"),
    path("<int:todo_id>/update/<int:comment_id>", views.update_comment_view, name="update_comment"),
    path("<int:todo_id>/delete/<int:comment_id>", views.delete_comment_view, name="delete_comment"),
    path("<int:todo_id>/likes/<int:comment_id>", views.likes_comment_view, name="likes_comment"),
]

todo/models.py
from django.db import models
from user.models import UserModel


class TodoModel(models.Model):
    # (Todo) N:1 (User)
    author = models.ForeignKey(UserModel, on_delete=models.CASCADE, related_name="todo")
    title = models.CharField(max_length=64)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    completed = models.BooleanField(default=False)
    # (Todo) N:N (User)
    likes = models.ManyToManyField(UserModel, related_name="likes_todo", blank=True)


class CommentModel(models.Model):
    # (Comment) N:1 (User)
    author = models.ForeignKey(
        UserModel, on_delete=models.CASCADE, related_name="comment"
    )
    # (Comment) N:1 (todo)
    todo = models.ForeignKey(
        TodoModel, on_delete=models.CASCADE, related_name="comment"
    )
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    # (Comment) N:N (User)
    likes = models.ManyToManyField(UserModel, related_name="likes_comment", blank=True)

todo/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.db.models import Count
from .models import CommentModel, TodoModel
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseNotAllowed


def home_view(request):
    if request.method == "GET":
        todos = TodoModel.objects.prefetch_related("likes").order_by("-created_at")
        return render(request, "todo/home.html", {"todos": todos})
    else:
        return HttpResponseNotAllowed(["GET"])


def detail_view(request, id):
    if request.method == "GET":
        todo = get_object_or_404(TodoModel, id=id)
        # 댓글을 좋아요, 최신순으로 정렬
        comments = (
            todo.comment.prefetch_related("likes")
            .annotate(count_likes=Count("likes"))
            .order_by("-count_likes", "-created_at")
        )
        return render(request, "todo/detail.html", {"todo": todo, "comments": comments})
    else:
        return HttpResponseNotAllowed(["GET"])


# todo
@login_required
def create_view(request):
    if request.method == "GET":
        return render(request, "todo/form.html")
    elif request.method == "POST":
        todo = TodoModel()
        todo.author = request.user
        todo.title = request.POST.get("title")
        todo.content = request.POST.get("content", "")
        todo.save()
        return redirect(reverse("todo:home"))
    else:
        return HttpResponseNotAllowed(["GET", "POST"])


@login_required
def update_view(request, id):
    if request.method == "GET":
        todo = get_object_or_404(TodoModel, id=id)
        if todo.author == request.user:
            return render(request, "todo/form.html", {"todo": todo})
        else:
            return redirect(reverse("todo:detail", args=[id]))
    elif request.method == "POST":
        todo = get_object_or_404(TodoModel, id=id)
        todo.title = request.POST.get("title")
        todo.content = request.POST.get("content", "")
        if request.POST.get("completed"):
            todo.completed = True
        else:
            todo.completed = False
        todo.save()
        return redirect(reverse("todo:detail", args=[id]))
    else:
        return HttpResponseNotAllowed(["GET", "POST"])


@login_required
def delete_view(request, id):
    if request.method == "POST":
        todo = get_object_or_404(TodoModel, id=id)
        if todo.author == request.user:
            todo.delete()
            return redirect(reverse("todo:home"))
        else:
            return redirect(reverse("todo:detail", args=[id]))
    else:
        return HttpResponseNotAllowed(["POST"])


@login_required
def mypage_view(request):
    if request.method == "GET":
        # TodoModel의 UserModel에 대한 역참조 이름 related_name = "todo"
        todos = request.user.todo.all().order_by("-created_at")
        return render(request, "todo/home.html", {"todos": todos})
    else:
        return HttpResponseNotAllowed(["GET"])


@login_required
def likes_view(request, id):
    if request.method == "POST":
        todo = get_object_or_404(TodoModel, id=id)
        user = request.user
        if user == todo.author:
            return redirect(reverse("todo:detail", args=[id]))
        # todo의 likes로 접근하면 해당 todo에 좋아요를 누른 유저 관리모델에 접근
        if user in todo.likes.all():
            todo.likes.remove(user)
        else:
            todo.likes.add(user)
        return redirect(reverse("todo:detail", args=[id]))
    else:
        return HttpResponseNotAllowed(["POST"])


# comment
@login_required
def create_comment_view(request, todo_id):
    if request.method == "POST":
        todo = get_object_or_404(TodoModel, id=todo_id)
        content = request.POST.get("content", "")
        # comment의 todo에 대한 역참조 이름 related_name="comment"
        todo.comment.create(content=content, author=request.user)
        return redirect(reverse("todo:detail", args=[todo_id]))
    else:
        return HttpResponseNotAllowed(["POST"])


@login_required
def update_comment_view(request, todo_id, comment_id):
    if request.method == "GET":
        # todo는 사용되지 않지만 todo가 존재하지 않으면 404 에러 응답하기 위함
        todo = get_object_or_404(TodoModel, id=todo_id)
        comment = get_object_or_404(CommentModel, id=comment_id)
        if comment.author == request.user:
            return render(
                request,
                "todo/comment_form.html",
                {"todo_id": todo_id, "comment": comment},
            )
        else:
            return redirect(reverse("todo:detail", args=[todo_id]))
    elif request.method == "POST":
        todo = get_object_or_404(TodoModel, id=todo_id)
        comment = get_object_or_404(CommentModel, id=comment_id)
        comment.content = request.POST.get("content", "")
        comment.save()
        # 업데이트된 댓글로 리다이렉트
        return redirect(
            reverse("todo:detail", args=[todo_id]) + f"#comment_{comment_id}"
        )
    else:
        return HttpResponseNotAllowed(["GET", "POST"])


@login_required
def delete_comment_view(request, todo_id, comment_id):
    if request.method == "POST":
        todo = get_object_or_404(TodoModel, id=todo_id)
        comment = get_object_or_404(CommentModel, id=comment_id)
        if comment.author == request.user:
            comment.delete()
        return redirect(reverse("todo:detail", args=[todo_id]))
    else:
        return HttpResponseNotAllowed(["POST"])


@login_required
def likes_comment_view(request, todo_id, comment_id):
    if request.method == "POST":
        todo = get_object_or_404(TodoModel, id=todo_id)
        comment = get_object_or_404(CommentModel, id=comment_id)
        user = request.user
        if user == comment.author:
            return redirect(reverse("todo:detail", args=[todo_id]))
        # comment.likes는 해당 댓글에 좋아요를 누른 유저 관리모델에 접근
        if user in comment.likes.all():
            comment.likes.remove(user)
        else:
            comment.likes.add(user)
        # 좋아요를 누른 댓글로 리다이렉트
        return redirect(
            reverse("todo:detail", args=[todo_id]) + f"#comment_{comment_id}"
        )
    else:
        return HttpResponseNotAllowed(["POST"])

templates/todo/comment_form.html
{% extends 'base.html' %}

{% block content %}
<!-- 댓글 수정 폼 -->
<div class="container my-3">
    <form method="post" action="{% url 'todo:update_comment' todo_id=todo_id comment_id=comment.id %}"> 
        {% csrf_token %}
        <div class="form-group">
            <label for="content">댓글</label>
            <textarea class="form-control" name="content" id="content" rows="4">{{ comment.content }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

templates/todo/detail.html
{% extends "base.html" %}

{% block content %}
<!-- Todo의 상세 정보 페이지 -->
<div class="container my-3">
    <h2 class="border-bottom py-2 mt-5">{{ todo.title }}</h2>
    {% if todo.completed %}
    <span class="badge badge-success">완료</span>
    {% else %}
    <span class="badge badge-light">미완료</span>
    {% endif %}
    <div class="card my-3">
        <div class="card-body">
            <div class="d-flex justify-content-end mb-3">
                <strong>by {{ todo.author.username }}</strong>
            </div>
        
            <div class="card-text">{{ todo.content }}</div>
        
            <div class="d-flex justify-content-end">
                <div class="badge badge-light text-dark p-2 text-start mx-3">
                    <div class="mb-2">수정됨</div>
                    <div>{{ todo.updated_at }}</div>
                </div>
                <div class="badge badge-light text-dark p-2 text-start">
                    <div class="mb-2">작성됨</div>
                    <div>{{ todo.created_at }}</div>
                </div>
            </div>
            
            <div class="my-3 d-flex">
                {% if user == todo.author %}
                <a class="btn btn-sm btn-primary" href="{% url 'todo:update' todo.id %}">수정</a>
                <form method="post" action="{% url 'todo:delete' todo.id %}">
                    {% csrf_token %}
                    <button class="btn btn-danger btn-sm ml-1" type="submit">삭제</button>
                </form>
                {% else %}
                <form method="post" action="{% url 'todo:likes' todo.id %}">
                    {% csrf_token %}
                    {% if user in todo.likes.all %}
                    <button class="btn btn-sm btn-secondary" type="submit">
                        추천 취소
                        <span class="badge rounded-pill bg-success">{{todo.likes.count}}</span>
                    </button>
                    {% else %}
                    <button class="btn btn-sm btn-primary" type="submit">
                        추천
                        <span class="badge rounded-pill bg-light">{{todo.likes.count}}</span>
                    </button>
                    {% endif %}
                </form>
                {% endif %}
            </div>
        </div>
    </div>

    <h5 class="border-bottom my-3 py-2">{{ comments.count }}개의 댓글</h5>
    {% for comment in comments %}
    <a id="comment_{{ comment.id }}"></a>
    <div class="card my-3">
        <div class="card-body">
            <div class="mb-4">
                <strong>{{ comment.author.username }}</strong>
            </div>
            <div class="card-text">{{ comment.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light text-dark p-2 text-start mx-3">
                    <div>{{ comment.created_at|timesince }} 전</div>
                </div>
            </div>
            <div class="my-3 d-flex">
                {% if user == comment.author %}
                <a class="btn btn-sm btn-primary" href="{% url 'todo:update_comment' todo_id=todo.id comment_id=comment.id %}">수정</a>
                <form method="post" action="{% url 'todo:delete_comment' todo_id=todo.id comment_id=comment.id %}">
                    {% csrf_token %}
                    <button class="btn btn-danger btn-sm ml-1" type="submit">삭제</button>
                </form>
                {% else %}
                <form method="post" action="{% url 'todo:likes_comment' todo_id=todo.id comment_id=comment.id %}">
                    {% csrf_token %}
                    {% if user in comment.likes.all %}
                    <button class="btn btn-sm btn-secondary" type="submit">
                        추천 취소
                        <span class="badge rounded-pill bg-success">{{comment.likes.count}}</span>
                    </button>
                    {% else %}
                    <button class="btn btn-sm btn-primary" type="submit">
                        추천
                        <span class="badge rounded-pill bg-light">{{comment.likes.count}}</span>
                    </button>
                    {% endif %}
                </form>
                {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}
    <form action="{% url 'todo:create_comment' todo_id=todo.id %}" method="post" class="my-3">
        {% csrf_token %}
        <div class="mb-3">
            <label for="content" class="form-label">댓글 남기기</label>
            <textarea {% if not user.is_authenticated %}disabled{% endif %}
                    name="content" id="content" class="form-control" rows="3"></textarea>
        </div>
        <input type="submit" value="등록" class="btn btn-primary">
    </form>
</div>
{% endblock %}

templates/todo/form.html
{% extends "base.html" %}

{% block content %}
<!-- Todo를 작성하거나 수정하는 페이지 -->
<div class="container mt-5">
    <h1 class="mb-4">Todo {% if todo %}수정{% else %}작성{% endif %}</h1>

    <form method="post" action="{% if todo %}{% url 'todo:update' todo.id %}{% else %}{% url 'todo:create' %}{% endif %}">
        {% csrf_token %}
        <div class="form-group">
            <label for="title">할 일</label>
            <input type="text" class="form-control" id="title" name="title" value="{{ todo.title }}">
        </div>
        <div class="form-group">
            <label for="content">내용</label>
            <textarea class="form-control" id="content" name="content" rows="4">{{ todo.content }}</textarea>
        </div>
        {% if todo %}
            <div class="form-group form-check">
                <input type="checkbox" class="form-check-input" id="completed" name="completed" {% if todo.completed %}checked{% endif %}>
                <label class="form-check-label" for="completed">완료!</label>
            </div>
        {% endif %}
        <button type="submit" class="btn btn-primary">저장</button>
    </form>
</div>
{% endblock %}

templates/todo/home.html
{% extends "base.html" %}

{% block content %}
<!-- Todo 리스트를 보여주는 홈페이지 -->
<div class="container mt-5">
    <h1 class="mb-4">Todo List</h1>

    {% if user.is_authenticated %}
    <a class="btn btn-primary" href="{% url 'todo:create' %}">Create</a>
    {% endif %}

    <table class="table mt-3">
        <thead>
            <tr>
                <th>제목</th>
                <th>추천</th>
                <th>저자</th>
                <th>완료 여부</th>
                <th>작성 시간</th>
            </tr>
        </thead>
        <tbody>
            {% for todo in todos %}
            <tr>
                <td>
                    <a href="{% url 'todo:detail' todo.id %}">{{ todo.title }}</a>
                    <span class="text-danger small mx-1">({{todo.comment.count}})</span>
                </td>
                <td>
                    {{ todo.likes.count }}
                </td>
                <td {% if user.is_authenticated and user == todo.author %}style="color: green;"{% endif %}>
                    {{ todo.author.username }}
                </td>
                <td>
                    {% if todo.completed %}
                    <span class="badge badge-success">완료</span>
                    {% else %}
                    <span class="badge badge-light">미완료</span>
                    {% endif %}
                </td>
                <td>
                    {{ todo.created_at | timesince }} 전
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}