config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("todo.urls", namespace="todo")),
    path("user/", include("user.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todo/urls.py
from django.urls import path
from . import views

app_name = "todo"

urlpatterns = [
    path("", views.home_view, name="home"),
    path("detail/<int:id>", views.detail_view, name="detail"),
    # todo
    path("create/", views.create_view, name="create"),
    path("update/<int:id>", views.update_view, name="update"),
    path("delete/<int:id>", views.delete_view, name="delete"),
    path("mypage/", views.mypage_view, name="mypage"),
    path("likes/<int:id>", views.likes_view, name="likes"),
    # comment
    path("<int:todo_id>/create", views.create_comment_view, name="create_comment"),
    path("<int:todo_id>/update/<int:comment_id>", views.update_comment_view, name="update_comment"),
    path("<int:todo_id>/delete/<int:comment_id>", views.delete_comment_view, name="delete_comment"),
    path("<int:todo_id>/likes/<int:comment_id>", views.likes_comment_view, name="likes_comment"),
]

user/urls.py
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path("signup/", views.signup_view, name="signup"),
    path("signin/", views.signin_view, name="signin"),
    path("logout/", views.logout_view, name="logout"),
    path("profile/", views.profile_view, name="profile"),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Todo List</title>
    <!-- Add Bootstrap CSS link here -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <!-- Navigation bar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'todo:home' %}"><strong>Home</strong></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                    <!-- 사용자가 로그인한 경우 -->
                    {% if user.profile_picture %}
                    <img src="{{ user.profile_picture.url }}" alt="프로필 사진" class="rounded" height="40px">
                    {% endif %}
                    <li class="nav-item">
                        <span class="nav-link disabled mr-4"><strong>환영합니다, {{ user.username }}님</strong></span>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'user:profile' %}">프로필 설정</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'todo:mypage' %}">나의 Todo보기</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'user:logout' %}">로그아웃</a>
                    </li>
                {% else %}
                    <!-- 사용자가 로그인하지 않은 경우 -->
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'user:signin' %}">로그인</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'user:signup' %}">회원가입</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>
    
    <!-- Content -->
    <div class="container mt-4">
        {% block content %}{% endblock %}
    </div>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>